# -*- coding: utf-8 -*-
"""ai-paper-to-article-GPT-3-2023-01-16-AV-v4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPtoJjS3VURgzyf6sGpZ3H-Ew4RLwsBX

# Generando un Artículo Científico en Español con GPT-3
# ai-paper-to-article-GPT-3-2023-01-16-AV-v4
Software developed by Aster Volta.
"""

# install necessary libraries
py -m pip install openai
"""--------

V4
"""
import streamlit as st
import openai

# insert your OpenAI API key here
openai.api_key = "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"

# define the prompt for the model
name_of_article = input("Nombre del artículo científico: ")
prompt = (f"Actúa como periodista científico y escribe un artículo en español para el público en general. Explica los resultados y proporciona números para respaldar tus afirmaciones. Acerca del artículo científico titulado {name_of_article}. Lang: es")

# generate text using the GPT-3 model
response = openai.Completion.create(
    engine="text-davinci-002",
    prompt=prompt,
    temperature=0.3,
    max_tokens=4030,
    n = 1,
    stop=None,
    top_p = 1,
    frequency_penalty = 1,
    presence_penalty = 0,
)


# print the generated text
print(response["choices"][0]["text"])

"""## **THE END ✨**"""
